from PyQt5 import QtCore, QtGui, QtWidgets

"""
    MODIFICA DEI PARAMETRI DEL PRODOTTO
    prende in input un prodotto e ne permette di modificare i campi (visualizzandone i vecchi?)
"""


class VistaModificaProdotto(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cerca = QtWidgets.QLineEdit(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cerca.sizePolicy().hasHeightForWidth())
        self.cerca.setSizePolicy(sizePolicy)
        self.cerca.setMinimumSize(QtCore.QSize(250, 0))
        self.cerca.setObjectName("cerca")
        self.gridLayout_3.addWidget(self.cerca, 0, 10, 1, 1)
        self.taglia = QtWidgets.QComboBox(self.widget_8)
        self.taglia.setObjectName("taglia")
        self.taglia.addItem("")
        self.gridLayout_3.addWidget(self.taglia, 3, 7, 1, 1)
        self.genere = QtWidgets.QComboBox(self.widget_8)
        self.genere.setObjectName("genere")
        self.genere.addItem("")
        self.genere.addItem("")
        self.genere.addItem("")
        self.genere.addItem("")
        self.gridLayout_3.addWidget(self.genere, 3, 6, 1, 1)
        self.in_arrivo = QtWidgets.QPushButton(self.widget_8)
        self.in_arrivo.setObjectName("in_arrivo")
        self.gridLayout_3.addWidget(self.in_arrivo, 1, 0, 1, 1)
        self.tipo = QtWidgets.QComboBox(self.widget_8)
        self.tipo.setObjectName("tipo")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.tipo.addItem("")
        self.gridLayout_3.addWidget(self.tipo, 3, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 7, 1, 1)
        self.in_negozio = QtWidgets.QPushButton(self.widget_8)
        self.in_negozio.setObjectName("in_negozio")
        self.gridLayout_3.addWidget(self.in_negozio, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.marca = QtWidgets.QComboBox(self.widget_8)
        self.marca.setPlaceholderText("")
        self.marca.setObjectName("marca")
        self.marca.addItem("")
        self.marca.addItem("")
        self.gridLayout_3.addWidget(self.marca, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 6, 1, 1)
        self.logo = QtWidgets.QLabel(self.widget_8)
        self.logo.setObjectName("logo")
        self.gridLayout_3.addWidget(self.logo, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.collezione = QtWidgets.QComboBox(self.widget_8)
        self.collezione.setObjectName("collezione")
        self.collezione.addItem("")
        self.collezione.addItem("")
        self.gridLayout_3.addWidget(self.collezione, 3, 8, 1, 1)
        self.venduto = QtWidgets.QPushButton(self.widget_8)
        self.venduto.setObjectName("venduto")
        self.gridLayout_3.addWidget(self.venduto, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 9, 1, 1)
        self.indietro = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indietro.sizePolicy().hasHeightForWidth())
        self.indietro.setSizePolicy(sizePolicy)
        self.indietro.setObjectName("indietro")
        self.gridLayout_3.addWidget(self.indietro, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 10, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 0, 1, 11)
        self.verticalLayout.addWidget(self.widget_8)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1172, 851))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.prima_colonna = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prima_colonna.sizePolicy().hasHeightForWidth())
        self.prima_colonna.setSizePolicy(sizePolicy)
        self.prima_colonna.setMinimumSize(QtCore.QSize(200, 400))
        self.prima_colonna.setObjectName("prima_colonna")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.prima_colonna)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.immagine = QtWidgets.QLabel(self.prima_colonna)
        self.immagine.setObjectName("immagine")
        self.verticalLayout_2.addWidget(self.immagine)
        self.nome_marca = QtWidgets.QLabel(self.prima_colonna)
        self.nome_marca.setObjectName("nome_marca")
        self.verticalLayout_2.addWidget(self.nome_marca)
        self.prezzo = QtWidgets.QLabel(self.prima_colonna)
        self.prezzo.setObjectName("prezzo")
        self.verticalLayout_2.addWidget(self.prezzo)
        self.gridLayout_2.addWidget(self.prima_colonna, 0, 0, 1, 1)
        self.terza_colonna = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terza_colonna.sizePolicy().hasHeightForWidth())
        self.terza_colonna.setSizePolicy(sizePolicy)
        self.terza_colonna.setMinimumSize(QtCore.QSize(200, 400))
        self.terza_colonna.setObjectName("terza_colonna")
        self.gridLayout_2.addWidget(self.terza_colonna, 0, 4, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 400))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(200, 400))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2.addWidget(self.widget_5, 2, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 2, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 2, 3, 1, 1)
        self.seconda_colonna = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seconda_colonna.sizePolicy().hasHeightForWidth())
        self.seconda_colonna.setSizePolicy(sizePolicy)
        self.seconda_colonna.setMinimumSize(QtCore.QSize(200, 400))
        self.seconda_colonna.setObjectName("seconda_colonna")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.seconda_colonna)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.immagine_2 = QtWidgets.QLabel(self.seconda_colonna)
        self.immagine_2.setObjectName("immagine_2")
        self.verticalLayout_3.addWidget(self.immagine_2)
        self.nome_marca_2 = QtWidgets.QLabel(self.seconda_colonna)
        self.nome_marca_2.setObjectName("nome_marca_2")
        self.verticalLayout_3.addWidget(self.nome_marca_2)
        self.prezzo_2 = QtWidgets.QLabel(self.seconda_colonna)
        self.prezzo_2.setObjectName("prezzo_2")
        self.verticalLayout_3.addWidget(self.prezzo_2)
        self.gridLayout_2.addWidget(self.seconda_colonna, 0, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(200, 400))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 2, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.taglia.setItemText(0, _translate("MainWindow", "Taglia"))
        self.genere.setItemText(0, _translate("MainWindow", "Uomo"))
        self.genere.setItemText(1, _translate("MainWindow", "Donna"))
        self.genere.setItemText(2, _translate("MainWindow", "Bambino"))
        self.genere.setItemText(3, _translate("MainWindow", "Bambina"))
        self.in_arrivo.setText(_translate("MainWindow", "IN ARRIVO"))
        self.tipo.setItemText(0, _translate("MainWindow", "Eleganti"))
        self.tipo.setItemText(1, _translate("MainWindow", "Sneakers"))
        self.tipo.setItemText(2, _translate("MainWindow", "Sportive"))
        self.tipo.setItemText(3, _translate("MainWindow", "Trekking"))
        self.in_negozio.setText(_translate("MainWindow", "IN NEGOZIO"))
        self.marca.setCurrentText(_translate("MainWindow", "Armani"))
        self.marca.setItemText(0, _translate("MainWindow", "Armani"))
        self.marca.setItemText(1, _translate("MainWindow", "Pier One"))
        self.logo.setText(_translate("MainWindow", "Logo"))
        self.collezione.setItemText(0, _translate("MainWindow", "Primavera/Estate"))
        self.collezione.setItemText(1, _translate("MainWindow", "Autunno/Inverno"))
        self.venduto.setText(_translate("MainWindow", "VENDUTO"))
        self.indietro.setText(_translate("MainWindow", "< Indietro"))
        self.pushButton_7.setText(_translate("MainWindow", "RESO"))
        self.immagine.setText(_translate("MainWindow", "TextLabel"))
        self.nome_marca.setText(_translate("MainWindow", "Marca - Nome prodotto"))
        self.prezzo.setText(_translate("MainWindow", "Prezzo"))
        self.immagine_2.setText(_translate("MainWindow", "TextLabel"))
        self.nome_marca_2.setText(_translate("MainWindow", "Marca - Nome prodotto"))
        self.prezzo_2.setText(_translate("MainWindow", "Prezzo"))


    """
            Eventi trigger click dei bottoni
    """

    def salva_modifiche_click(self):
        # campo1 = self.lineEdit_9.text()
        # self.controller.set_nome_fornitore(campo1)
        self.update_ui()
        self.close()

    def show_back_click(self):
        self.close()
