import sys

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import QDate
from PyQt5.QtWidgets import QWidget, QMessageBox


class VistaModificaUtente(QWidget):
    def __init__(self, utente, controller, controller_lista, update_ui_utente):
        super(VistaModificaUtente, self).__init__()
        self.utente_selezionato= utente
        self.controller= controller
        self.controller_lista= controller_lista
        self.update_ui_utente= update_ui_utente

        # boolean che permette di eseguire due eventi diversi in casi di chiusura
        self.end1= False

        lista = self.controller_lista.get_lista_del_personale()
        self.new_lista_del_personale = lista[:]
        # affinche non ci siano problemi con il controllo in save_data() (controllo sull'inserimento di un fornitore con stesso codice)
        # ho bisogno di una lista che non contenga il fornitore che sto modificando
        self.new_lista_del_personale.remove(self.utente_selezionato)

        ###################################

        ''' 
            Costruzione parte statica dell'interfaccia
        '''
        self.setObjectName("Form")
        self.resize(626, 464)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\emili\\Documents\\QtDesigner\\test\\../../../Pictures/Screenshots/Screenshot (206).png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.setWindowIcon(icon)
        self.setWindowTitle("Modifica utente")
        self.gridLayout_3 = QtWidgets.QGridLayout(self)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_salva = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_salva.sizePolicy().hasHeightForWidth())
        self.pushButton_salva.setSizePolicy(sizePolicy)
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.pushButton_salva.setDefault(True)
        self.pushButton_salva.clicked.connect(self.save_data)
        self.horizontalLayout_3.addWidget(self.pushButton_salva)
        self.pushButton_salva.setStyleSheet("QPushButton {\n""   background-color: rgb(26, 108, 218);\n""   border-width: 2px;\n""   border-radius: 10px;\n""   font: bold 12px;\n""   padding: 6px;\n""   color: white;\n""}")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_annulla = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_annulla.sizePolicy().hasHeightForWidth())
        self.pushButton_annulla.setSizePolicy(sizePolicy)
        self.pushButton_annulla.setObjectName("pushButton_annulla")
        self.pushButton_annulla.clicked.connect(self.close)
        self.horizontalLayout_3.addWidget(self.pushButton_annulla)
        self.pushButton_annulla.setStyleSheet("QPushButton {\n" "   background-color:white;\n" "   border-width: 2px;\n""   border-radius: 10px;\n""   border: 2px solid gray;\n""   font: bold 12px;\n""   padding: 6px;\n""}")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_data_nascita = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_nascita.sizePolicy().hasHeightForWidth())
        self.label_data_nascita.setSizePolicy(sizePolicy)
        self.label_data_nascita.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_nascita.setMaximumSize(QtCore.QSize(153, 30))
        self.label_data_nascita.setObjectName("label_data_nascita")
        self.gridLayout_2.addWidget(self.label_data_nascita, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.label_data_scadenza_contratto = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_scadenza_contratto.sizePolicy().hasHeightForWidth())
        self.label_data_scadenza_contratto.setSizePolicy(sizePolicy)
        self.label_data_scadenza_contratto.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_scadenza_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_scadenza_contratto.setObjectName("label_data_scadenza_contratto")
        self.gridLayout_2.addWidget(self.label_data_scadenza_contratto, 8, 3, 1, 1)
        self.lineEdit_codice = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_codice.sizePolicy().hasHeightForWidth())
        self.lineEdit_codice.setSizePolicy(sizePolicy)
        self.lineEdit_codice.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_codice.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_codice.setObjectName("lineEdit_codice")
        self.gridLayout_2.addWidget(self.lineEdit_codice, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem4, 10, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)

        self.dateEdit_nascita = QtWidgets.QDateEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_nascita.sizePolicy().hasHeightForWidth())
        self.dateEdit_nascita.setSizePolicy(sizePolicy)
        self.dateEdit_nascita.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit_nascita.setObjectName("dateEdit_nascita")
        self.gridLayout_2.addWidget(self.dateEdit_nascita, 6, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 5, 1, 1)
        self.label_luogo_nascita = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_luogo_nascita.sizePolicy().hasHeightForWidth())
        self.label_luogo_nascita.setSizePolicy(sizePolicy)
        self.label_luogo_nascita.setMinimumSize(QtCore.QSize(0, 20))
        self.label_luogo_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_luogo_nascita.setObjectName("label_luogo_nascita")
        self.gridLayout_2.addWidget(self.label_luogo_nascita, 5, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem8, 13, 3, 1, 1)

        self.label_indirizzo = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_indirizzo.sizePolicy().hasHeightForWidth())
        self.label_indirizzo.setSizePolicy(sizePolicy)
        self.label_indirizzo.setMinimumSize(QtCore.QSize(0, 20))
        self.label_indirizzo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_indirizzo.setObjectName("label_indirizzo")
        self.gridLayout_2.addWidget(self.label_indirizzo, 11, 1, 1, 1)
        self.label_cf = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cf.sizePolicy().hasHeightForWidth())
        self.label_cf.setSizePolicy(sizePolicy)
        self.label_cf.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_cf.setObjectName("label_cf")
        self.gridLayout_2.addWidget(self.label_cf, 5, 5, 1, 1)
        self.label_cognome = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cognome.sizePolicy().hasHeightForWidth())
        self.label_cognome.setSizePolicy(sizePolicy)
        self.label_cognome.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cognome.setMaximumSize(QtCore.QSize(153, 30))
        self.label_cognome.setObjectName("label_cognome")
        self.gridLayout_2.addWidget(self.label_cognome, 1, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 2, 4, 1, 1)
        self.label_ruolo = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ruolo.sizePolicy().hasHeightForWidth())
        self.label_ruolo.setSizePolicy(sizePolicy)
        self.label_ruolo.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ruolo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_ruolo.setObjectName("label_ruolo")
        self.gridLayout_2.addWidget(self.label_ruolo, 8, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum,
                                             QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem10, 0, 3, 1, 3)
        self.dateEdit_inizio_contratto = QtWidgets.QDateEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_inizio_contratto.sizePolicy().hasHeightForWidth())
        self.dateEdit_inizio_contratto.setSizePolicy(sizePolicy)
        self.dateEdit_inizio_contratto.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit_inizio_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit_inizio_contratto.setObjectName("dateEdit_inizio_contratto")
        self.gridLayout_2.addWidget(self.dateEdit_inizio_contratto, 9, 1, 1, 1)
        self.lineEdit_indirizzo = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_indirizzo.sizePolicy().hasHeightForWidth())
        self.lineEdit_indirizzo.setSizePolicy(sizePolicy)
        self.lineEdit_indirizzo.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_indirizzo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_indirizzo.setObjectName("lineEdit_indirizzo")
        self.gridLayout_2.addWidget(self.lineEdit_indirizzo, 12, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                             QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem11, 7, 3, 1, 1)
        self.lineEdit_stipendio = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_stipendio.sizePolicy().hasHeightForWidth())
        self.lineEdit_stipendio.setSizePolicy(sizePolicy)
        self.lineEdit_stipendio.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_stipendio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_stipendio.setObjectName("lineEdit_stipendio")
        self.gridLayout_2.addWidget(self.lineEdit_stipendio, 12, 5, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nome.sizePolicy().hasHeightForWidth())
        self.lineEdit_nome.setSizePolicy(sizePolicy)
        self.lineEdit_nome.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout_2.addWidget(self.lineEdit_nome, 2, 3, 1, 1)
        self.lineEdit_cognome = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cognome.sizePolicy().hasHeightForWidth())
        self.lineEdit_cognome.setSizePolicy(sizePolicy)
        self.lineEdit_cognome.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_cognome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_cognome.setObjectName("lineEdit_cognome")
        self.gridLayout_2.addWidget(self.lineEdit_cognome, 2, 5, 1, 1)

        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 2, 6, 1, 1)
        self.label_data_inizio_contratto = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_inizio_contratto.sizePolicy().hasHeightForWidth())
        self.label_data_inizio_contratto.setSizePolicy(sizePolicy)
        self.label_data_inizio_contratto.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_inizio_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_inizio_contratto.setObjectName("label_data_inizio_contratto")
        self.gridLayout_2.addWidget(self.label_data_inizio_contratto, 8, 1, 1, 1)
        self.lineEdit_telefono = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_telefono.sizePolicy().hasHeightForWidth())
        self.lineEdit_telefono.setSizePolicy(sizePolicy)
        self.lineEdit_telefono.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_telefono.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.gridLayout_2.addWidget(self.lineEdit_telefono, 12, 3, 1, 1)
        self.dateEdit_scadenza_contratto = QtWidgets.QDateEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_scadenza_contratto.sizePolicy().hasHeightForWidth())
        self.dateEdit_scadenza_contratto.setSizePolicy(sizePolicy)
        self.dateEdit_scadenza_contratto.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit_scadenza_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit_scadenza_contratto.setObjectName("dateEdit_scadenza_contratto")
        self.gridLayout_2.addWidget(self.dateEdit_scadenza_contratto, 9, 3, 1, 1)

        self.comboBox_ruolo = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ruolo.sizePolicy().hasHeightForWidth())
        self.comboBox_ruolo.setSizePolicy(sizePolicy)
        self.comboBox_ruolo.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_ruolo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_ruolo.setObjectName("comboBox_ruolo")
        self.comboBox_ruolo.addItem("Dipendente")
        self.comboBox_ruolo.addItem("Amministratore")
        self.gridLayout_2.addWidget(self.comboBox_ruolo, 9, 5, 1, 1)
        self.label_codice = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_codice.sizePolicy().hasHeightForWidth())
        self.label_codice.setSizePolicy(sizePolicy)
        self.label_codice.setMinimumSize(QtCore.QSize(0, 20))
        self.label_codice.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_codice.setObjectName("label_codice")
        self.gridLayout_2.addWidget(self.label_codice, 1, 1, 1, 1)
        self.label_telefono = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_telefono.sizePolicy().hasHeightForWidth())
        self.label_telefono.setSizePolicy(sizePolicy)
        self.label_telefono.setMinimumSize(QtCore.QSize(0, 20))
        self.label_telefono.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_telefono.setObjectName("label_telefono")
        self.gridLayout_2.addWidget(self.label_telefono, 11, 3, 1, 1)
        self.lineEdit_luogo_nascita = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_luogo_nascita.sizePolicy().hasHeightForWidth())
        self.lineEdit_luogo_nascita.setSizePolicy(sizePolicy)
        self.lineEdit_luogo_nascita.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_luogo_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_luogo_nascita.setObjectName("lineEdit_luogo_nascita")
        self.gridLayout_2.addWidget(self.lineEdit_luogo_nascita, 6, 3, 1, 1)
        self.lineEdit_cf = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cf.sizePolicy().hasHeightForWidth())
        self.lineEdit_cf.setSizePolicy(sizePolicy)
        self.lineEdit_cf.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_cf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_cf.setObjectName("lineEdit_cf")
        self.gridLayout_2.addWidget(self.lineEdit_cf, 6, 5, 1, 1)
        self.label_stipendio = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stipendio.sizePolicy().hasHeightForWidth())
        self.label_stipendio.setSizePolicy(sizePolicy)
        self.label_stipendio.setMinimumSize(QtCore.QSize(0, 20))
        self.label_stipendio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_stipendio.setObjectName("label_stipendio")
        self.gridLayout_2.addWidget(self.label_stipendio, 11, 5, 1, 1)
        self.label_nome = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nome.sizePolicy().hasHeightForWidth())
        self.label_nome.setSizePolicy(sizePolicy)
        self.label_nome.setMinimumSize(QtCore.QSize(0, 20))
        self.label_nome.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_nome.setObjectName("label_nome")
        self.gridLayout_2.addWidget(self.label_nome, 1, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                             QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem13, 16, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.contatore=0
        self.setWindowTitle("Modifica utente")
        self.retranslateUi()
        self.comboBox_ruolo.currentIndexChanged.connect(self.retranslateUi_2)

        QtCore.QMetaObject.connectSlotsByName(self)

    '''
        Costruzione parte dinamica dell'interfaccia  
    '''
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_salva.setText(_translate("Form", "Salva"))
        self.pushButton_annulla.setText(_translate("Form", "Annulla"))

        self.label_codice.setText(_translate("Form", "Codice"))
        self.lineEdit_codice.setText(_translate("Form", str(self.controller.get_cod_utente())))
        self.label_nome.setText(_translate("Form", "Nome"))
        self.lineEdit_nome.setText(_translate("Form", str(self.controller.get_nome())))
        self.label_cognome.setText(_translate("Form", "Cognome"))
        self.lineEdit_cognome.setText(_translate("Form", str(self.controller.get_cognome())))
        self.label_data_nascita.setText(_translate("Form", "Data di nascita"))
        data_nascita = self.controller.get_data_nascita()
        data_nascita_split = data_nascita.split("/")
        self.dateEdit_nascita.setDate(QDate(int(data_nascita_split[2]), int(data_nascita_split[1]), int(data_nascita_split[0])))
        self.label_luogo_nascita.setText(_translate("Form", "Luogo di nascita"))
        self.lineEdit_luogo_nascita.setText(_translate("Form", str(self.controller.get_luogo_nascita())))
        self.label_cf.setText(_translate("Form", "Codice fiscale"))
        self.lineEdit_cf.setText(_translate("Form", str(self.controller.get_cf())))
        self.label_data_inizio_contratto.setText(_translate("Form", "Data inizio contratto"))
        data_inizio_contratto = self.controller.get_data_inizio_contratto()
        data_inizio_contratto_split = data_inizio_contratto.split("/")
        self.dateEdit_inizio_contratto.setDate(QDate(int(data_inizio_contratto_split[2]), int(data_inizio_contratto_split[1]), int(data_inizio_contratto_split[0])))
        self.label_data_scadenza_contratto.setText(_translate("Form", "Data scadenza contratto"))
        data_scadenza_contratto = self.controller.get_data_scadenza_contratto()
        data_scadenza_contratto_split = data_scadenza_contratto.split("/")
        self.dateEdit_scadenza_contratto.setDate(QDate(int(data_scadenza_contratto_split[2]), int(data_scadenza_contratto_split[1]), int(data_scadenza_contratto_split[0])))
        self.label_ruolo.setText(_translate("Form", "Ruolo"))
        self.comboBox_ruolo.setItemText(0, _translate("Form", "Dipendente"))
        self.comboBox_ruolo.setItemText(1, _translate("Form", "Amministratore"))

        if self.controller.get_ruolo() == "Dipendente":
            index = self.comboBox_ruolo.findText("Dipendente", QtCore.Qt.MatchFixedString)
        else:
            index = self.comboBox_ruolo.findText("Amministratore", QtCore.Qt.MatchFixedString)
        self.comboBox_ruolo.setCurrentIndex(index)

        self.label_indirizzo.setText(_translate("Form", "Indirizzo"))
        self.lineEdit_indirizzo.setText(_translate("Form", str(self.controller.get_indirizzo())))
        self.label_telefono.setText(_translate("Form", "Telefono"))
        self.lineEdit_telefono.setText(_translate("Form", str(self.controller.get_telefono())))
        self.label_stipendio.setText(_translate("Form", "Stipendio"))
        self.lineEdit_stipendio.setText(_translate("Form", str(self.controller.get_stipendio())))

        self.retranslateUi_2()

    '''Metodo: crea e aggiunge le componenti dinamiche label e lineEdit di username e password'''
    def retranslateUi_2(self):
        # indica se sto chiamando per la prima volta il metodo retranslate
        self.contatore= self.contatore+1

        _translate = QtCore.QCoreApplication.translate
        if self.comboBox_ruolo.currentText()=="Amministratore":
            #------------
            self.label_username = QtWidgets.QLabel(self)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_username.sizePolicy().hasHeightForWidth())
            self.label_username.setSizePolicy(sizePolicy)
            self.label_username.setMinimumSize(QtCore.QSize(0, 20))
            self.label_username.setMaximumSize(QtCore.QSize(16777215, 30))
            self.label_username.setObjectName("label_username")
            self.label_username.setText(_translate("Form", "Username"))
            #-------------
            self.lineEdit_username = QtWidgets.QLineEdit(self)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_username.sizePolicy().hasHeightForWidth())
            self.lineEdit_username.setSizePolicy(sizePolicy)
            self.lineEdit_username.setMinimumSize(QtCore.QSize(150, 0))
            self.lineEdit_username.setMaximumSize(QtCore.QSize(16777215, 30))
            self.lineEdit_username.setObjectName("lineEdit_username")
            self.lineEdit_username.setText(_translate("Form", str(self.controller.get_username())))
            #--------------
            self.label_password = QtWidgets.QLabel(self)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_password.sizePolicy().hasHeightForWidth())
            self.label_password.setSizePolicy(sizePolicy)
            self.label_password.setMinimumSize(QtCore.QSize(0, 20))
            self.label_password.setMaximumSize(QtCore.QSize(16777215, 30))
            self.label_password.setObjectName("label_password")
            self.label_password.setText(_translate("Form", "Password"))
            #--------------
            self.lineEdit_password = QtWidgets.QLineEdit(self)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.lineEdit_password.sizePolicy().hasHeightForWidth())
            self.lineEdit_password.setSizePolicy(sizePolicy)
            self.lineEdit_password.setMinimumSize(QtCore.QSize(150, 0))
            self.lineEdit_password.setMaximumSize(QtCore.QSize(16777215, 30))
            self.lineEdit_password.setObjectName("lineEdit_password")
            self.lineEdit_password.setText(_translate("Form", str(self.controller.get_password())))
            #--------------
            self.gridLayout_2.addWidget(self.label_username, 14, 1, 1, 1)
            self.gridLayout_2.addWidget(self.lineEdit_username, 15, 1, 1, 1)
            self.gridLayout_2.addWidget(self.label_password, 14, 3, 1, 1)
            self.gridLayout_2.addWidget(self.lineEdit_password, 15, 3, 1, 1)
        elif self.contatore!=1:
            self.gridLayout_2.removeWidget(self.label_username)
            self.label_username.deleteLater()
            self.gridLayout_2.removeWidget(self.lineEdit_username)
            self.lineEdit_username.deleteLater()
            self.gridLayout_2.removeWidget(self.label_password)
            self.label_password.deleteLater()
            self.gridLayout_2.removeWidget(self.lineEdit_password)
            self.lineEdit_password.deleteLater()

    def save_data(self):
        self.end1= True
        for utente in self.new_lista_del_personale:
            if str(utente.cod_utente)==self.lineEdit_codice.text() or utente.cf== self.lineEdit_cf.text():
                QMessageBox.critical(self, 'Errore', 'Utente già presente in lista!', QMessageBox.Ok, QMessageBox.Ok)
                return

        #prendo il testo che l'utente inserisce in ciascuna lineEdit
        codice = self.lineEdit_codice.text()
        nome= self.lineEdit_nome.text()
        cognome= self.lineEdit_cognome.text()
        dd_n= str(self.dateEdit_nascita.date().day())
        mm_n= str(self.dateEdit_nascita.date().month())
        aaaa_n= str(self.dateEdit_nascita.date().year())
        data_nascita= dd_n + "/" + mm_n + "/" + aaaa_n
        luogo_nascita= self.lineEdit_luogo_nascita.text()
        cf= self.lineEdit_cf.text()
        dd_i = str(self.dateEdit_inizio_contratto.date().day())
        mm_i = str(self.dateEdit_inizio_contratto.date().month())
        aaaa_i = str(self.dateEdit_inizio_contratto.date().year())
        data_inizio_contratto = dd_i + "/" + mm_i + "/" + aaaa_i
        dd_s = str(self.dateEdit_scadenza_contratto.date().day())
        mm_s = str(self.dateEdit_scadenza_contratto.date().month())
        aaaa_s = str(self.dateEdit_scadenza_contratto.date().year())
        data_scadenza_contratto = dd_s + "/" + mm_s + "/" + aaaa_s
        ruolo = str(self.comboBox_ruolo.currentText())
        indirizzo= self.lineEdit_indirizzo.text()
        telefono= self.lineEdit_telefono.text()
        stipendio= self.lineEdit_stipendio.text()

        #E' necessario settare ruolo QUI
        self.controller.set_ruolo(ruolo)
        if self.comboBox_ruolo.currentText()== "Amministratore":
            username= self.lineEdit_username.text()
            self.controller.set_username(username)
            password= self.lineEdit_password.text()
            self.controller.set_password(password)
        else:
            self.controller.set_username(None)
            self.controller.set_password(None)

        #modifico gli attributi del fornitore in base al testo inserito
        self.controller.set_cod_utente(codice)
        self.controller.set_nome(nome)
        self.controller.set_cognome(cognome)
        self.controller.set_data_nascita(data_nascita)
        self.controller.set_luogo_nascita(luogo_nascita)
        self.controller.set_cf(cf)
        self.controller.set_data_inizio_contratto(data_inizio_contratto)
        self.controller.set_data_scadenza_contratto(data_scadenza_contratto)
        self.controller.set_indirizzo(indirizzo)
        self.controller.set_telefono(telefono)
        self.controller.set_stipendio(stipendio)

        self.update_ui_utente()
        self.close()
        self.end1= False

    def closeEvent(self, event):
        if self.end1==False:
            reply = QMessageBox.question(self, 'Annullare?',
                                         'Sicuro di voler annullare? Tutte le modifiche andranno perse.',
                                         QMessageBox.Yes | QMessageBox.No, QMessageBox.No)

            if reply == QMessageBox.Yes:
                if not type(event) == bool:
                    event.accept()
                else:
                    sys.exit()
            else:
                if not type(event) == bool:
                    event.ignore()
