from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget


class VistaModificaUtente(QWidget):
    def __init__(self, controller, update_ui_utente, parent=None):
        super(VistaModificaUtente, self).__init__(parent)
        self.controller= controller
        self.update_ui_utente= update_ui_utente

        self.setObjectName("Form")
        self.resize(575, 468)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(400, 400, 160, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        '''
            
        '''
        self.pushButton_salva = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.horizontalLayout_3.addWidget(self.pushButton_salva)
        self.pushButton_salva.clicked.connect(self.save_data())

        self.pushButton_annulla = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_annulla.setObjectName("pushButton_annulla")
        self.horizontalLayout_3.addWidget(self.pushButton_annulla)
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 491, 332))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_data_scadenza_contratto = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_data_scadenza_contratto.setObjectName("lineEdit_data_scadenza_contratto")
        self.gridLayout_2.addWidget(self.lineEdit_data_scadenza_contratto, 16, 3, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout_2.addWidget(self.lineEdit_nome, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.lineEdit_codice = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_codice.setObjectName("lineEdit_codice")
        self.gridLayout_2.addWidget(self.lineEdit_codice, 12, 0, 1, 1)
        self.lineEdit_cf = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cf.setObjectName("lineEdit_cf")
        self.gridLayout_2.addWidget(self.lineEdit_cf, 7, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 11, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 9, 5, 1, 1)
        self.lineEdit_eta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_eta.setObjectName("lineEdit_eta")
        self.gridLayout_2.addWidget(self.lineEdit_eta, 7, 3, 1, 1)
        self.label_data_scadenza_contratto = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_data_scadenza_contratto.setObjectName("label_data_scadenza_contratto")
        self.gridLayout_2.addWidget(self.label_data_scadenza_contratto, 15, 3, 1, 1)
        self.lineEdit_cognome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cognome.setObjectName("lineEdit_cognome")
        self.gridLayout_2.addWidget(self.lineEdit_cognome, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 4, 1, 1)
        self.label_data_nascita = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_data_nascita.setObjectName("label_data_nascita")
        self.gridLayout_2.addWidget(self.label_data_nascita, 1, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 8, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 8, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 4, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 4, 3, 1, 1)
        self.label_luogo_nascita = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_luogo_nascita.setObjectName("label_luogo_nascita")
        self.gridLayout_2.addWidget(self.label_luogo_nascita, 6, 0, 1, 1)
        self.label_nome = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_nome.setObjectName("label_nome")
        self.gridLayout_2.addWidget(self.label_nome, 1, 0, 1, 1)
        self.label_cognome = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_cognome.setObjectName("label_cognome")
        self.gridLayout_2.addWidget(self.label_cognome, 1, 3, 1, 1)
        self.label_codice = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_codice.setObjectName("label_codice")
        self.gridLayout_2.addWidget(self.label_codice, 11, 0, 1, 1)
        self.label_ruolo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ruolo.setObjectName("label_ruolo")
        self.gridLayout_2.addWidget(self.label_ruolo, 11, 5, 1, 1)
        self.comboBox_ruolo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_ruolo.setObjectName("comboBox_ruolo")
        self.comboBox_ruolo.addItem("")
        self.comboBox_ruolo.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_ruolo, 12, 5, 1, 1)
        self.lineEdit_luogo_nascita = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_luogo_nascita.setObjectName("lineEdit_luogo_nascita")
        self.gridLayout_2.addWidget(self.lineEdit_luogo_nascita, 7, 0, 1, 1)
        self.lineEdit_stipendio = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_stipendio.setObjectName("lineEdit_stipendio")
        self.gridLayout_2.addWidget(self.lineEdit_stipendio, 16, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 1, 1, 1, 1)
        self.label_cf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_cf.setObjectName("label_cf")
        self.gridLayout_2.addWidget(self.label_cf, 6, 5, 1, 1)
        self.label_stipendio = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_stipendio.setObjectName("label_stipendio")
        self.gridLayout_2.addWidget(self.label_stipendio, 15, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 11, 4, 1, 1)
        self.lineEdit_telefono = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.gridLayout_2.addWidget(self.lineEdit_telefono, 12, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 9, 3, 1, 1)
        self.label_telefono = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_telefono.setObjectName("label_telefono")
        self.gridLayout_2.addWidget(self.label_telefono, 11, 3, 1, 1)
        self.lineEdit_data_nascita = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_data_nascita.setObjectName("lineEdit_data_nascita")
        self.gridLayout_2.addWidget(self.lineEdit_data_nascita, 2, 5, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 6, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 3, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 14, 0, 1, 1)
        self.label_eta = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_eta.setObjectName("label_eta")
        self.gridLayout_2.addWidget(self.label_eta, 6, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 8, 5, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 6, 4, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 3, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 13, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 13, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 14, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 13, 5, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 14, 5, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Modifica utente"))
        self.pushButton_salva.setText(_translate("Form", "Salva"))
        self.pushButton_annulla.setText(_translate("Form", "Annulla"))
        self.lineEdit_data_scadenza_contratto.setText(_translate("Form", self.controller.get_data_scadenza_contratto()))
        self.lineEdit_nome.setText(_translate("Form", self.controller.get_nome()))
        self.lineEdit_codice.setText(_translate("Form", self.controller.get_codice_utente()))
        self.lineEdit_cf.setText(_translate("Form", self.controller.get_cf()))
        self.lineEdit_eta.setText(_translate("Form", self.controller.get_eta()))
        self.label_data_scadenza_contratto.setText(_translate("Form", "Data scadenza contratto"))
        self.lineEdit_cognome.setText(_translate("Form", self.controller.get_cognome()))
        self.label_data_nascita.setText(_translate("Form", "Data di nascita"))
        self.label_luogo_nascita.setText(_translate("Form", "Luogo di nascita"))
        self.label_nome.setText(_translate("Form", "Nome"))
        self.label_cognome.setText(_translate("Form", "Cognome"))
        self.label_codice.setText(_translate("Form", "Codice"))
        self.label_ruolo.setText(_translate("Form", "Ruolo"))
        self.comboBox_ruolo.setItemText(0, _translate("Form", "Dipendente"))
        self.comboBox_ruolo.setItemText(1, _translate("Form", "Amministratore"))
        self.lineEdit_luogo_nascita.setText(_translate("Form", self.controller.get_luogo_nascita()))
        self.lineEdit_stipendio.setText(_translate("Form", self.controller.get_stipendio()))
        self.label_cf.setText(_translate("Form", "Codice fiscale"))
        self.label_stipendio.setText(_translate("Form", "Stipendio"))
        self.lineEdit_telefono.setText(_translate("Form", self.controller.get_telefono()))
        self.label_telefono.setText(_translate("Form", "Telefono"))
        self.lineEdit_data_nascita.setText(_translate("Form", self.controller.get_data_nascita()))
        self.label_eta.setText(_translate("Form", "Età"))

    def save_data(self):
        #prendo il testo che l'utente inserisce in ciascuna lineEdit
        nome= self.lineEdit_nome.text()
        cognome= self.lineEdit_cognome.text()
        data_nascita= self.lineEdit_data_nascita.text()
        luogo_nascita= self.lineEdit_luogo_nascita.text()
        eta= self.lineEdit_eta.text()
        cf= self.lineEdit_cf.text()
        codice= self.lineEdit_codice.text()
        telefono= self.lineEdit_telefono.text()
        ruolo= self.li
        partita_iva = self.lineEdit_9.text()
        indirizzo = self.lineEdit_10.text()
        telefono = self.lineEdit_11.text()
        email = self.lineEdit_12.text()
        data_affiliazione = self.lineEdit_13.text()
        rappresentante = self.lineEdit_14.text()
        nome = self.lineEdit_15.text()
        codice = self.lineEdit_16.text()
        stato = str(self.comboBox_2.currentText())

        #modifico gli attributi del fornitore in base al testo inserito
        self.controller.set_nome(nome)
        self.controller.set_telefono(telefono)
        self.controller.set_indirizzo(indirizzo)
        self.controller.set_partita_iva(partita_iva)
        self.controller.set_email(email)
        self.controller.set_rappresentante(rappresentante)
        self.controller.set_data_affiliazione(data_affiliazione)
        self.controller.set_codice(codice)
        self.controller.set_stato(stato)

        #aggiorno (in teoria) ahahah
        self.update_ui_utente()
        self.close()