from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QWidget


class VistaModificaUtente(QWidget):
    def __init__(self, controller, update_ui_utente, parent=None):
        super(VistaModificaUtente, self).__init__(parent)
        self.controller= controller
        self.update_ui_utente= update_ui_utente

        self.setObjectName("Form")
        self.resize(626, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\emili\\Documents\\QtDesigner\\test\\../../../Pictures/Screenshots/Screenshot (206).png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(self)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)

        # Tasto SALVA
        self.pushButton_salva = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_salva.sizePolicy().hasHeightForWidth())
        self.pushButton_salva.setSizePolicy(sizePolicy)
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.horizontalLayout_3.addWidget(self.pushButton_salva)
        self.pushButton_salva.clicked.connect(self.save_data)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)

        # Tasto ANNULLA
        self.pushButton_annulla = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_annulla.sizePolicy().hasHeightForWidth())
        self.pushButton_annulla.setSizePolicy(sizePolicy)
        self.pushButton_annulla.setObjectName("pushButton_annulla")
        self.horizontalLayout_3.addWidget(self.pushButton_annulla)
        self.pushButton_annulla.clicked.connect(self.close)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_luogo_nascita = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_luogo_nascita.sizePolicy().hasHeightForWidth())
        self.lineEdit_luogo_nascita.setSizePolicy(sizePolicy)
        self.lineEdit_luogo_nascita.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_luogo_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_luogo_nascita.setObjectName("lineEdit_luogo_nascita")
        self.gridLayout_2.addWidget(self.lineEdit_luogo_nascita, 6, 1, 1, 1)
        self.lineEdit_telefono = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_telefono.sizePolicy().hasHeightForWidth())
        self.lineEdit_telefono.setSizePolicy(sizePolicy)
        self.lineEdit_telefono.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_telefono.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.gridLayout_2.addWidget(self.lineEdit_telefono, 9, 3, 1, 1)
        self.dateEdit_nascita = QtWidgets.QDateEdit(self)
        self.dateEdit_nascita.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit_nascita.setObjectName("dateEdit_nascita")
        self.gridLayout_2.addWidget(self.dateEdit_nascita, 2, 5, 1, 1)
        self.label_cf = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cf.sizePolicy().hasHeightForWidth())
        self.label_cf.setSizePolicy(sizePolicy)
        self.label_cf.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_cf.setObjectName("label_cf")
        self.gridLayout_2.addWidget(self.label_cf, 5, 5, 1, 1)
        self.label_eta = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_eta.sizePolicy().hasHeightForWidth())
        self.label_eta.setSizePolicy(sizePolicy)
        self.label_eta.setMinimumSize(QtCore.QSize(0, 20))
        self.label_eta.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_eta.setObjectName("label_eta")
        self.gridLayout_2.addWidget(self.label_eta, 5, 3, 1, 1)
        self.label_telefono = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_telefono.sizePolicy().hasHeightForWidth())
        self.label_telefono.setSizePolicy(sizePolicy)
        self.label_telefono.setMinimumSize(QtCore.QSize(0, 20))
        self.label_telefono.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_telefono.setObjectName("label_telefono")
        self.gridLayout_2.addWidget(self.label_telefono, 8, 3, 1, 1)
        self.lineEdit_cognome = QtWidgets.QLineEdit(self)
        self.lineEdit_cognome.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_cognome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_cognome.setObjectName("lineEdit_cognome")
        self.gridLayout_2.addWidget(self.lineEdit_cognome, 2, 3, 1, 1)
        self.label_ruolo = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ruolo.sizePolicy().hasHeightForWidth())
        self.label_ruolo.setSizePolicy(sizePolicy)
        self.label_ruolo.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ruolo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_ruolo.setObjectName("label_ruolo")
        self.gridLayout_2.addWidget(self.label_ruolo, 8, 5, 1, 1)
        self.label_data_scadenza_contratto = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_scadenza_contratto.sizePolicy().hasHeightForWidth())
        self.label_data_scadenza_contratto.setSizePolicy(sizePolicy)
        self.label_data_scadenza_contratto.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_scadenza_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_scadenza_contratto.setObjectName("label_data_scadenza_contratto")
        self.gridLayout_2.addWidget(self.label_data_scadenza_contratto, 11, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem4, 10, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem7, 7, 1, 1, 1)
        self.lineEdit_stipendio = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_stipendio.sizePolicy().hasHeightForWidth())
        self.lineEdit_stipendio.setSizePolicy(sizePolicy)
        self.lineEdit_stipendio.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_stipendio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_stipendio.setObjectName("lineEdit_stipendio")
        self.gridLayout_2.addWidget(self.lineEdit_stipendio, 12, 1, 1, 1)
        self.comboBox_ruolo = QtWidgets.QComboBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ruolo.sizePolicy().hasHeightForWidth())
        self.comboBox_ruolo.setSizePolicy(sizePolicy)
        self.comboBox_ruolo.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_ruolo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_ruolo.setObjectName("comboBox_ruolo")
        self.comboBox_ruolo.addItem("")
        self.comboBox_ruolo.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_ruolo, 9, 5, 1, 1)
        self.label_nome = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nome.sizePolicy().hasHeightForWidth())
        self.label_nome.setSizePolicy(sizePolicy)
        self.label_nome.setMinimumSize(QtCore.QSize(0, 20))
        self.label_nome.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_nome.setObjectName("label_nome")
        self.gridLayout_2.addWidget(self.label_nome, 1, 1, 1, 1)
        self.label_luogo_nascita = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_luogo_nascita.sizePolicy().hasHeightForWidth())
        self.label_luogo_nascita.setSizePolicy(sizePolicy)
        self.label_luogo_nascita.setMinimumSize(QtCore.QSize(0, 20))
        self.label_luogo_nascita.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_luogo_nascita.setObjectName("label_luogo_nascita")
        self.gridLayout_2.addWidget(self.label_luogo_nascita, 5, 1, 1, 1)
        self.label_stipendio = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stipendio.sizePolicy().hasHeightForWidth())
        self.label_stipendio.setSizePolicy(sizePolicy)
        self.label_stipendio.setMinimumSize(QtCore.QSize(0, 20))
        self.label_stipendio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_stipendio.setObjectName("label_stipendio")
        self.gridLayout_2.addWidget(self.label_stipendio, 11, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 3, 5, 1, 1)
        self.lineEdit_eta = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_eta.sizePolicy().hasHeightForWidth())
        self.lineEdit_eta.setSizePolicy(sizePolicy)
        self.lineEdit_eta.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_eta.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_eta.setObjectName("lineEdit_eta")
        self.gridLayout_2.addWidget(self.lineEdit_eta, 6, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem9, 13, 1, 1, 5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 2, 0, 1, 1)
        self.label_codice = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_codice.sizePolicy().hasHeightForWidth())
        self.label_codice.setSizePolicy(sizePolicy)
        self.label_codice.setMinimumSize(QtCore.QSize(0, 20))
        self.label_codice.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_codice.setObjectName("label_codice")
        self.gridLayout_2.addWidget(self.label_codice, 8, 1, 1, 1)
        self.label_cognome = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cognome.sizePolicy().hasHeightForWidth())
        self.label_cognome.setSizePolicy(sizePolicy)
        self.label_cognome.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cognome.setMaximumSize(QtCore.QSize(153, 30))
        self.label_cognome.setObjectName("label_cognome")
        self.gridLayout_2.addWidget(self.label_cognome, 1, 3, 1, 1)
        self.lineEdit_codice = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_codice.sizePolicy().hasHeightForWidth())
        self.lineEdit_codice.setSizePolicy(sizePolicy)
        self.lineEdit_codice.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_codice.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_codice.setObjectName("lineEdit_codice")
        self.gridLayout_2.addWidget(self.lineEdit_codice, 9, 1, 1, 1)
        self.lineEdit_cf = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cf.sizePolicy().hasHeightForWidth())
        self.lineEdit_cf.setSizePolicy(sizePolicy)
        self.lineEdit_cf.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_cf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_cf.setObjectName("lineEdit_cf")
        self.gridLayout_2.addWidget(self.lineEdit_cf, 6, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 2, 1, 1)
        self.lineEdit_nome = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nome.sizePolicy().hasHeightForWidth())
        self.lineEdit_nome.setSizePolicy(sizePolicy)
        self.lineEdit_nome.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.gridLayout_2.addWidget(self.lineEdit_nome, 2, 1, 1, 1)
        self.dateEdit_scadenza_contratto = QtWidgets.QDateEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_scadenza_contratto.sizePolicy().hasHeightForWidth())
        self.dateEdit_scadenza_contratto.setSizePolicy(sizePolicy)
        self.dateEdit_scadenza_contratto.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit_scadenza_contratto.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit_scadenza_contratto.setObjectName("dateEdit_scadenza_contratto")
        self.gridLayout_2.addWidget(self.dateEdit_scadenza_contratto, 12, 3, 1, 1)
        self.label_data_nascita = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_nascita.sizePolicy().hasHeightForWidth())
        self.label_data_nascita.setSizePolicy(sizePolicy)
        self.label_data_nascita.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_nascita.setMaximumSize(QtCore.QSize(153, 30))
        self.label_data_nascita.setObjectName("label_data_nascita")
        self.gridLayout_2.addWidget(self.label_data_nascita, 1, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum,
                                             QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 5)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Modifica utente"))
        self.pushButton_salva.setText(_translate("Form", "Salva"))
        self.pushButton_annulla.setText(_translate("Form", "Annulla"))
        self.lineEdit_luogo_nascita.setText(_translate("Form", str(self.controller.get_luogo_nascita())))
        self.lineEdit_telefono.setText(_translate("Form", str(self.controller.get_telefono())))
        self.label_cf.setText(_translate("Form", "Codice fiscale"))
        self.label_eta.setText(_translate("Form", "Età"))
        self.label_telefono.setText(_translate("Form", "Telefono"))
        self.lineEdit_cognome.setText(_translate("Form", str(self.controller.get_cognome())))
        self.label_ruolo.setText(_translate("Form", "Ruolo"))
        self.label_data_scadenza_contratto.setText(_translate("Form", "Data scadenza contratto"))
        self.lineEdit_stipendio.setText(_translate("Form", str(self.controller.get_stipendio())))
        self.comboBox_ruolo.setItemText(0, _translate("Form", "Dipendente"))
        self.comboBox_ruolo.setItemText(1, _translate("Form", "Amministratore"))
        if self.controller.get_ruolo()=="Dipendente":
            index= self.comboBox_ruolo.findText("Dipendente", QtCore.Qt.MatchFixedString)
        else:
            index= self.comboBox_ruolo.findText("Amministratore", QtCore.Qt.MatchFixedString)
        self.comboBox_ruolo.setCurrentIndex(index)

        self.label_nome.setText(_translate("Form", "Nome"))
        self.label_luogo_nascita.setText(_translate("Form", "Luogo di nascita"))
        self.label_stipendio.setText(_translate("Form", "Stipendio"))
        self.lineEdit_eta.setText(_translate("Form", str(self.controller.get_eta())))
        self.label_codice.setText(_translate("Form", "Codice"))
        self.label_cognome.setText(_translate("Form", "Cognome"))
        self.lineEdit_codice.setText(_translate("Form", str(self.controller.get_cod_utente())))
        self.lineEdit_cf.setText(_translate("Form", str(self.controller.get_cf())))
        self.lineEdit_nome.setText(_translate("Form", str(self.controller.get_nome())))
        self.label_data_nascita.setText(_translate("Form", "Data di nascita"))

    def save_data(self):
        #prendo il testo che l'utente inserisce in ciascuna lineEdit
        nome= self.lineEdit_nome.text()
        cognome= self.lineEdit_cognome.text()
        dd_n= str(self.dateEdit_nascita.date().day())
        mm_n= str(self.dateEdit_nascita.date().month())
        aaaa_n= str(self.dateEdit_nascita.date().year())
        data_nascita= dd_n + "/" + mm_n + "/" + aaaa_n
        luogo_nascita= self.lineEdit_luogo_nascita.text()
        eta= self.lineEdit_eta.text()
        cf= self.lineEdit_cf.text()
        codice= self.lineEdit_codice.text()
        telefono= self.lineEdit_telefono.text()
        ruolo= str(self.comboBox_ruolo.currentText())
        stipendio= self.lineEdit_stipendio.text()
        dd_s= str(self.dateEdit_scadenza_contratto.date().day())
        mm_s = str(self.dateEdit_scadenza_contratto.date().month())
        aaaa_s = str(self.dateEdit_scadenza_contratto.date().year())
        data_scadenza_contratto= dd_s + "/" + mm_s+ "/" + aaaa_s

        #modifico gli attributi del fornitore in base al testo inserito
        self.controller.set_nome(nome)
        self.controller.set_cognome(cognome)
        self.controller.set_data_nascita(data_nascita)
        self.controller.set_luogo_nascita(luogo_nascita)
        self.controller.set_eta(eta)
        self.controller.set_cf(cf)
        self.controller.set_cod_utente(codice)
        self.controller.set_telefono(telefono)
        self.controller.set_ruolo(ruolo)
        self.controller.set_stipendio(stipendio)
        self.controller.set_data_scadenza_contratto(data_scadenza_contratto)

        #aggiorno (in teoria) ahahah
        self.update_ui_utente()
        self.close()