from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QComboBox, QLabel, QStyleFactory, QApplication, QCheckBox, QHBoxLayout, QGridLayout, \
    QGroupBox, QWidget, QHBoxLayout


# prende in input un prodotto e ne permette di modificare i campi visualizzando i vecchi
class VistaModificaOrdine(QWidget):
    def __init__(self, cod_prodotto, parent=None):
        super(VistaModificaOrdine, self).__init__(parent)
        self.cod_prodotto = cod_prodotto

        self.originalPalette = QApplication.palette()

        ################################
        self.setObjectName("Form")
        self.resize(722, 539)
        self.gridLayout_4 = QtWidgets.QGridLayout(self)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 13, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 4, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 12, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 8, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 12, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 12, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 14, 1, 1, 4)
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem6, 9, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 8, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 8, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "inserisci ordine  "))
        self.label_5.setText(_translate("Form", "importo totale "))
        self.label_9.setText(_translate("Form", "data arrivo prevista"))
        self.label_8.setText(_translate("Form", "calzature totali "))
        self.label_2.setText(_translate("Form", "codice fornitore "))
        self.label_4.setText(_translate("Form", "data arrivo effettiva "))
        self.pushButton.setText(_translate("Form", "annulla"))
        self.pushButton_2.setText(_translate("Form", "salva "))
        self.label.setText(_translate("Form", "Codice fattura"))
        self.label_7.setText(_translate("Form", "stato "))
        self.label_6.setText(_translate("Form", "data ordine "))
        self.label_3.setText(_translate("Form", "stagione "))
        ################################
    #     styleComboBox = QComboBox()
    #     styleComboBox.addItems(QStyleFactory.keys())
    #
    #     styleLabel = QLabel("&Style:")
    #     styleLabel.setBuddy(styleComboBox)
    #
    #     self.createTopLeftGroupBox()
    #     self.createTopRightGroupBox()
    #     self.createBottomLeftTabWidget()
    #     self.createBottomRightGroupBox()
    #     #self.createProgressBar()
    #
    #     styleComboBox.activated[str].connect(self.changeStyle)
    #
    #     topLayout = QHBoxLayout()
    #     topLayout.addWidget(styleLabel)
    #     topLayout.addWidget(styleComboBox)
    #
    #     mainLayout = QGridLayout()
    #     mainLayout.addLayout(topLayout, 0, 0, 1, 2)
    #     mainLayout.addWidget(self.topLeftGroupBox, 1, 0)
    #     mainLayout.addWidget(self.topRightGroupBox, 1, 1)
    #     mainLayout.addWidget(self.bottomLeftTabWidget, 2, 0)
    #     mainLayout.addWidget(self.bottomRightGroupBox, 2, 1)
    #     mainLayout.addWidget(self.progressBar, 3, 0, 1, 2)
    #     mainLayout.setRowStretch(1, 1)
    #     mainLayout.setRowStretch(2, 1)
    #     mainLayout.setColumnStretch(0, 1)
    #     mainLayout.setColumnStretch(1, 1)
    #     self.setLayout(mainLayout)
    #
    #     self.setWindowTitle("Modifica ordine")
    #     self.changeStyle('Windows')
    #
    # def createTopLeftGroupBox(self):
    #     self.topLeftGroupBox = QGroupBox("Group 1")
    #
    # def createTopRightGroupBox(self):
    #     self.topRightGroupBox = QGroupBox("Group 2")
    #
    # def createBottomLeftTabWidget(self):
    #     self.bottomLeftTabWidget = QGroupBox("Group 3")
    #
    # def createBottomRightGroupBox(self):
    #     self.bottomRightGroupBox = QGroupBox("Group 4")
