from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import QDate
from PyQt5.QtWidgets import QComboBox, QLabel, QStyleFactory, QApplication, QCheckBox, QHBoxLayout, QGridLayout, \
    QGroupBox, QWidget, QHBoxLayout, QTableWidgetItem


# prende in input un prodotto e ne permette di modificare i campi visualizzando i vecchi
class VistaModificaOrdine(QWidget):
    def __init__(self, ordine, controller, update_ui, lista_prodotti_ordine, parent=None):
        super(VistaModificaOrdine, self).__init__(parent)
        self.controller= controller
        self.update_ui_ordine= update_ui
        self.ordine_selezionato= ordine
        self.lista_prodotti_ordine= lista_prodotti_ordine
        self.lista_prodotti_ordine_dinamica= self.lista_prodotti_ordine[:]

        self.setObjectName("Form")
        self.resize(962, 780)
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit_arrivo_prevista = QtWidgets.QDateEdit(self)
        self.dateEdit_arrivo_prevista.setMaximumSize(QtCore.QSize(250, 16777215))
        self.dateEdit_arrivo_prevista.setObjectName("dateEdit_arrivo_prevista")
        self.gridLayout.addWidget(self.dateEdit_arrivo_prevista, 17, 0, 1, 1)
        self.label_cod_fornitore = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cod_fornitore.sizePolicy().hasHeightForWidth())
        self.label_cod_fornitore.setSizePolicy(sizePolicy)
        self.label_cod_fornitore.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cod_fornitore.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_cod_fornitore.setObjectName("label_cod_fornitore")
        self.gridLayout.addWidget(self.label_cod_fornitore, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 1)
        self.label_calzature_totali = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calzature_totali.sizePolicy().hasHeightForWidth())
        self.label_calzature_totali.setSizePolicy(sizePolicy)
        self.label_calzature_totali.setMinimumSize(QtCore.QSize(0, 20))
        self.label_calzature_totali.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_calzature_totali.setObjectName("label_calzature_totali")
        self.gridLayout.addWidget(self.label_calzature_totali, 24, 0, 1, 1)
        self.label_stagione = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stagione.sizePolicy().hasHeightForWidth())
        self.label_stagione.setSizePolicy(sizePolicy)
        self.label_stagione.setMinimumSize(QtCore.QSize(0, 20))
        self.label_stagione.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_stagione.setObjectName("label_stagione")
        self.gridLayout.addWidget(self.label_stagione, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_data_arrivo_prevista = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_arrivo_prevista.sizePolicy().hasHeightForWidth())
        self.label_data_arrivo_prevista.setSizePolicy(sizePolicy)
        self.label_data_arrivo_prevista.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_arrivo_prevista.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_arrivo_prevista.setObjectName("label_data_arrivo_prevista")
        self.gridLayout.addWidget(self.label_data_arrivo_prevista, 16, 0, 1, 1)
        self.label_cod_fattura = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cod_fattura.sizePolicy().hasHeightForWidth())
        self.label_cod_fattura.setSizePolicy(sizePolicy)
        self.label_cod_fattura.setMinimumSize(QtCore.QSize(200, 20))
        self.label_cod_fattura.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_cod_fattura.setObjectName("label_cod_fattura")
        self.gridLayout.addWidget(self.label_cod_fattura, 1, 0, 1, 1)
        self.lineEdit_cod_fornitore = QtWidgets.QLineEdit(self)
        self.lineEdit_cod_fornitore.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_cod_fornitore.setText("")
        self.lineEdit_cod_fornitore.setObjectName("lineEdit_cod_fornitore")
        self.gridLayout.addWidget(self.lineEdit_cod_fornitore, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 18, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 21, 0, 1, 1)
        self.label_data_arrivo_effettiva = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_arrivo_effettiva.sizePolicy().hasHeightForWidth())
        self.label_data_arrivo_effettiva.setSizePolicy(sizePolicy)
        self.label_data_arrivo_effettiva.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_arrivo_effettiva.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_arrivo_effettiva.setObjectName("label_data_arrivo_effettiva")
        self.gridLayout.addWidget(self.label_data_arrivo_effettiva, 19, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.lineEdit_cod_fattura = QtWidgets.QLineEdit(self)
        self.lineEdit_cod_fattura.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_cod_fattura.setText("")
        self.lineEdit_cod_fattura.setObjectName("lineEdit_cod_fattura")
        self.gridLayout.addWidget(self.lineEdit_cod_fattura, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 6, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 26, 0, 1, 7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 9, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 23, 0, 1, 1)
        self.label_data_ordine = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_ordine.sizePolicy().hasHeightForWidth())
        self.label_data_ordine.setSizePolicy(sizePolicy)
        self.label_data_ordine.setMinimumSize(QtCore.QSize(0, 20))
        self.label_data_ordine.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_ordine.setObjectName("label_data_ordine")
        self.gridLayout.addWidget(self.label_data_ordine, 13, 0, 1, 1)
        self.dateEdit_arrivo_effettiva = QtWidgets.QDateEdit(self)
        self.dateEdit_arrivo_effettiva.setMaximumSize(QtCore.QSize(250, 16777215))
        self.dateEdit_arrivo_effettiva.setObjectName("dateEdit_arrivo_effettiva")
        self.gridLayout.addWidget(self.dateEdit_arrivo_effettiva, 20, 0, 1, 1)
        self.dateEdit_ordine = QtWidgets.QDateEdit(self)
        self.dateEdit_ordine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.dateEdit_ordine.setObjectName("dateEdit_ordine")
        self.gridLayout.addWidget(self.dateEdit_ordine, 14, 0, 1, 1)
        self.pushButton_apri = QtWidgets.QPushButton(self)
        self.pushButton_apri.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_apri.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton_apri.setObjectName("pushButton_apri")
        self.gridLayout.addWidget(self.pushButton_apri, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 0, 0, 1, 7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 12, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 1, 25, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.pushButton_salva = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_salva.sizePolicy().hasHeightForWidth())
        self.pushButton_salva.setSizePolicy(sizePolicy)
        self.pushButton_salva.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.horizontalLayout.addWidget(self.pushButton_salva)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.pushButton_annulla = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_annulla.sizePolicy().hasHeightForWidth())
        self.pushButton_annulla.setSizePolicy(sizePolicy)
        self.pushButton_annulla.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_annulla.setObjectName("pushButton_annulla")
        self.horizontalLayout.addWidget(self.pushButton_annulla)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout, 31, 0, 1, 7)
        self.label_stato = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stato.sizePolicy().hasHeightForWidth())
        self.label_stato.setSizePolicy(sizePolicy)
        self.label_stato.setMinimumSize(QtCore.QSize(0, 20))
        self.label_stato.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_stato.setObjectName("label_stato")
        self.gridLayout.addWidget(self.label_stato, 10, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 1, 3, 1, 1)
        self.comboBox_stagione = QtWidgets.QComboBox(self)
        self.comboBox_stagione.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBox_stagione.setObjectName("comboBox_stagione")
        self.comboBox_stagione.addItem("")
        self.comboBox_stagione.addItem("")
        self.gridLayout.addWidget(self.comboBox_stagione, 8, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 1, 5, 1, 1)
        self.label_importo_totale = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_importo_totale.sizePolicy().hasHeightForWidth())
        self.label_importo_totale.setSizePolicy(sizePolicy)
        self.label_importo_totale.setMinimumSize(QtCore.QSize(0, 20))
        self.label_importo_totale.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_importo_totale.setObjectName("label_importo_totale")
        self.gridLayout.addWidget(self.label_importo_totale, 22, 0, 1, 1)
        self.comboBox_stato = QtWidgets.QComboBox(self)
        self.comboBox_stato.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBox_stato.setObjectName("comboBox_stato")
        self.comboBox_stato.addItem("")
        self.comboBox_stato.addItem("")
        self.gridLayout.addWidget(self.comboBox_stato, 11, 0, 1, 1)
        self.pushButton_nuovo = QtWidgets.QPushButton(self)
        self.pushButton_nuovo.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_nuovo.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton_nuovo.setObjectName("pushButton_nuovo")
        self.gridLayout.addWidget(self.pushButton_nuovo, 1, 6, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setMinimumSize(QtCore.QSize(710, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tableWidget, 2, 2, 24, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setWindowTitle("Modifica ordine")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_cod_fornitore.setText(_translate("Form", "Codice fornitore"))
        self.lineEdit_cod_fornitore.setText(_translate("Form", str(self.controller.get_cod_fornitore())))
        self.label_calzature_totali.setText(_translate("Form", "Calzature totali: {}".format(str(self.controller.get_calzature_totali()))))
        self.label_stagione.setText(_translate("Form", "Stagione"))
        self.label_data_arrivo_prevista.setText(_translate("Form", "Data arrivo prevista"))
        self.label_cod_fattura.setText(_translate("Form", "Codice fattura"))
        self.label_data_arrivo_effettiva.setText(_translate("Form", "Data arrivo effettiva"))
        self.label_10.setText(_translate("Form", "Lista prodotti ordine:"))
        self.label_data_ordine.setText(_translate("Form", "Data ordine"))
        self.pushButton_apri.setText(_translate("Form", "Apri"))
        self.pushButton_salva.setText(_translate("Form", "Salva"))
        self.pushButton_annulla.setText(_translate("Form", "Annulla"))
        self.label_stato.setText(_translate("Form", "Stato"))

        self.lineEdit_cod_fattura.setText(_translate("Form", str(self.controller.get_cod_fattura())))

        self.comboBox_stagione.setItemText(0, _translate("Form", "Primaverile/Estiva"))
        self.comboBox_stagione.setItemText(1, _translate("Form", "Autunnale/Invernale"))
        if self.controller.get_stagione()=="P/E":
            index= self.comboBox_stagione.findText("Primaverile/Estiva", QtCore.Qt.MatchFixedString)
        else:
            index= self.comboBox_stagione.findText("Autunnale/Invernale", QtCore.Qt.MatchFixedString)
        self.comboBox_stagione.setCurrentIndex(index)

        self.label_importo_totale.setText(_translate("Form", "Importo totale: {}".format(str(self.controller.get_importo_totale()))))

        self.comboBox_stato.setItemText(0, _translate("Form", "In arrivo"))
        self.comboBox_stato.setItemText(1, _translate("Form", "In negozio"))
        if self.controller.get_stato()=="In arrivo":
            index= self.comboBox_stato.findText("In arrivo", QtCore.Qt.MatchFixedString)
        else:
            index= self.comboBox_stato.findText("In negozio", QtCore.Qt.MatchFixedString)
        self.comboBox_stato.setCurrentIndex(index)

        data_ordine = self.controller.get_data_ordine()
        data_ordine_split = data_ordine.split("-")
        self.dateEdit_ordine.setDate(QDate(int(data_ordine_split[0]), int(data_ordine_split[1]), int(data_ordine_split[2])))

        data_arrivo_prevista = self.controller.get_data_arrivo_prevista()
        data_arrivo_prevista_split = data_arrivo_prevista.split("-")
        self.dateEdit_arrivo_prevista.setDate(QDate(int(data_arrivo_prevista_split[0]), int(data_arrivo_prevista_split[1]), int(data_arrivo_prevista_split[2])))

        data_arrivo_effettiva = self.controller.get_data_arrivo_effettiva()
        data_arrivo_effettiva_split = data_arrivo_effettiva.split("-")
        self.dateEdit_arrivo_effettiva.setDate(QDate(int(data_arrivo_effettiva_split[0]), int(data_arrivo_effettiva_split[1]),int(data_arrivo_effettiva_split[2])))

        self.pushButton_nuovo.setText(_translate("Form", "Inserisci prodotto"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codice prodotto"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Marca"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tipo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Quantità"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Taglia"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Prezzo d\'acquisto"))

        row = 0
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(len(self.lista_prodotti_ordine_dinamica))
        for prodotto in self.lista_prodotti_ordine_dinamica:
            item = QTableWidgetItem(str(prodotto.cod_prodotto))
            item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(item))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(prodotto.marca))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(prodotto.tipo))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(prodotto.quantita)))
            self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(prodotto.taglia)))
            self.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(str(prodotto.prezzo_acquisto) + " €"))

            row = row + 1

    def show_inserisci_prodotto(self):
        pass

    def save_data(self):
        pass